// AUTO-GENERATED by scripts/audit/gen-prop-tests.mjs from scripts/audit/props/model.json.
// Do not hand-edit — rerun the generator. All assertion logic lives in
// ../test-driver (scripts/audit/props/test-driver.tsx).
import model from '../model.json';
import { runComponentPropTests } from '../test-driver';

const componentModel = model.components.find((c) => c.slug === "chip");

if (!componentModel) {
  test.skip("chip: no model entry", () => {});
} else {
  runComponentPropTests("chip", componentModel);
}
