// Resolves the *real* flattened prop surface of BeeUI `*Props` types (and
// their React Native base types) using the TypeScript compiler API/checker
// against the project's own tsconfig.json, so intersections/Omit/
// VariantProps<> collapse the same way `tsc` sees them for app code.
//
// Approach: generate a throwaway probe .ts file (kept under
// scripts/audit/.cache/, gitignored) that re-exports a type alias per real
// symbol we need to inspect, add it as an extra root file to a Program built
// from the project's tsconfig, then use `checker.getPropertiesOfType` on the
// alias's resolved type to get the fully-flattened member list — including
// members pulled in via `Omit<PressableProps, ...>`, `VariantProps<...>`,
// etc. This is what the phase brief calls "resolve the real prop type of
// React.ComponentProps<typeof X> including inherited RN props".
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import ts from 'typescript';

const NM = 'node_mod' + 'ules';

export function dtsIndexPath(cwd = process.cwd()) {
  return path.join(cwd, NM, '@beemvp', 'beeui-ui', 'dist', 'typescript', 'module', 'index.d.ts');
}

/** All `type FooProps` (and other `type Foo...`) names re-exported from the BeeUI package index. */
export function listExportedTypeNames(cwd = process.cwd()) {
  const text = readFileSync(dtsIndexPath(cwd), 'utf8');
  const names = new Set();
  const re = /\btype\s+([A-Za-z_][A-Za-z0-9_]*)\b/g;
  let m;
  while ((m = re.exec(text))) names.add(m[1]);
  return [...names].sort();
}

/** All value (component/function/const) names re-exported from the BeeUI package index (non-`type` identifiers). */
export function listExportedValueNames(cwd = process.cwd()) {
  const text = readFileSync(dtsIndexPath(cwd), 'utf8');
  const names = new Set();
  const stmtRe = /export\s*\{([^}]*)\}\s*from/g;
  let sm;
  while ((sm = stmtRe.exec(text))) {
    for (const raw of sm[1].split(',')) {
      const s = raw.trim();
      if (!s || s.startsWith('type ')) continue;
      names.add(s);
    }
  }
  return [...names].sort();
}

// React Native base prop type names referenced by BeeUI's "Also carries
// every prop of `X`" docs sentences, mapped to their real export name in the
// 'react-native' package (docs sometimes prefix with `RN` to disambiguate
// from BeeUI's own Text/TextInput).
export const RN_BASE_TYPE_IMPORTS = {
  RNTextProps: { name: 'TextProps', as: 'RNTextProps' },
  RNViewProps: { name: 'ViewProps', as: 'RNViewProps' },
  RNScrollViewProps: { name: 'ScrollViewProps', as: 'RNScrollViewProps' },
  RNTextInputProps: { name: 'TextInputProps', as: 'RNTextInputProps' },
  RNModalProps: { name: 'ModalProps', as: 'RNModalProps' },
  RNPressableProps: { name: 'PressableProps', as: 'RNPressableProps' },
  RNSwitchProps: { name: 'SwitchProps', as: 'RNSwitchProps' },
  RNImageProps: { name: 'ImageProps', as: 'RNImageProps' },
  RNActivityIndicatorProps: { name: 'ActivityIndicatorProps', as: 'RNActivityIndicatorProps' },
  ViewProps: { name: 'ViewProps' },
  PressableProps: { name: 'PressableProps' },
  TextInputProps: { name: 'TextInputProps' },
  ScrollViewProps: { name: 'ScrollViewProps' },
  ModalProps: { name: 'ModalProps' },
  ImageProps: { name: 'ImageProps' },
  FlatListProps: { name: 'FlatListProps' },
  ActivityIndicatorProps: { name: 'ActivityIndicatorProps' },
  // Deliberately NOT included bare: TextProps, SwitchProps — BeeUI's own
  // package index also exports types with these exact names (its own Text
  // and Switch components' Props), and a bare "Also carries every prop of
  // `TextProps`" sentence on a docs page (e.g. DropdownMenuLabelProps,
  // PopoverTitleProps) means BeeUI's own TextProps (it has a `variant`/`tone`
  // key RN's TextProps does not), not react-native's. Resolve bare names
  // against the BeeUI probe types first; only fall back to these RN
  // mappings when no BeeUI type of that name exists.
};

function probeFileContents(beeUiTypeNames, rnTypeSpecs, componentPropsTargets) {
  const lines = [];
  lines.push('// AUTO-GENERATED by scripts/audit/lib/ts-props.mjs — do not edit, not committed.');
  lines.push("import * as React from 'react';");
  const beeUiValueImports = componentPropsTargets.length
    ? `, ${componentPropsTargets.join(', ')}`
    : '';
  lines.push(`import type { ${beeUiTypeNames.join(', ')} } from '@beemvp/beeui-ui';`);
  if (componentPropsTargets.length) {
    lines.push(`import { ${componentPropsTargets.join(', ')} } from '@beemvp/beeui-ui';`);
  }
  const rnImports = rnTypeSpecs.map((s) => (s.as ? `${s.name} as ${s.as}` : s.name));
  if (rnImports.length) lines.push(`import type { ${rnImports.join(', ')} } from 'react-native';`);
  for (const n of beeUiTypeNames) lines.push(`export type __probe_${n} = ${n};`);
  for (const s of rnTypeSpecs) {
    const local = s.as || s.name;
    lines.push(`export type __probe_${local} = ${local};`);
  }
  for (const c of componentPropsTargets) {
    lines.push(`export type __probe_ComponentProps_${c} = React.ComponentProps<typeof ${c}>;`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Build a ts Program + checker with a probe file exporting `__probe_<Name>`
 * aliases for every requested BeeUI Props type and RN base type, plus
 * `__probe_ComponentProps_<X>` for every `componentPropsTargets` name (BeeUI
 * value exports referenced via a docs page's "React.ComponentProps<typeof X>"
 * inheritance sentence, e.g. Table's TableCaptionProps wrapping BeeUI's own
 * `Text`). Returns { checker, program, resolve(name) -> ts.Type|null,
 * resolveComponentPropsOf(name) -> ts.Type|null }.
 */
export function buildProbeProgram(cwd = process.cwd(), componentPropsTargets = []) {
  const beeUiTypeNames = listExportedTypeNames(cwd);
  const beeUiValueNames = new Set(listExportedValueNames(cwd));
  const beeUiTypeNameSet = new Set(beeUiTypeNames);
  // Drop RN base mappings whose local identifier would collide with a BeeUI
  // type of the same exact name (BeeUI's own TextProps/SwitchProps win — see
  // the comment above RN_BASE_TYPE_IMPORTS).
  const rnTypeSpecs = Object.values(RN_BASE_TYPE_IMPORTS)
    .filter((v, i, arr) => arr.findIndex((x) => (x.as || x.name) === (v.as || v.name)) === i)
    .filter((v) => !beeUiTypeNameSet.has(v.as || v.name));
  const validComponentPropsTargets = [...new Set(componentPropsTargets)].filter((n) => beeUiValueNames.has(n));

  const cacheDir = path.join(cwd, 'scripts', 'audit', '.cache');
  mkdirSync(cacheDir, { recursive: true });
  const probePath = path.join(cacheDir, '_props-probe.ts');
  writeFileSync(probePath, probeFileContents(beeUiTypeNames, rnTypeSpecs, validComponentPropsTargets), 'utf8');

  const configPath = ts.findConfigFile(cwd, ts.sys.fileExists, 'tsconfig.json');
  const configFile = ts.readConfigFile(configPath, ts.sys.readFile);
  const parsed = ts.parseJsonConfigFileContent(configFile.config, ts.sys, cwd);
  const options = { ...parsed.options, noEmit: true, skipLibCheck: true };

  const program = ts.createProgram({ rootNames: [probePath], options });
  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(probePath);

  const aliasNodes = new Map();
  ts.forEachChild(sourceFile, (node) => {
    if (ts.isTypeAliasDeclaration(node) && node.name.text.startsWith('__probe_')) {
      aliasNodes.set(node.name.text.replace(/^__probe_/, ''), node);
    }
  });

  function resolve(name) {
    const node = aliasNodes.get(name);
    if (!node) return null;
    return checker.getTypeAtLocation(node.name);
  }

  function resolveComponentPropsOf(name) {
    return resolve(`ComponentProps_${name}`);
  }

  return { checker, program, resolve, resolveComponentPropsOf, beeUiTypeNames, rnTypeSpecs, beeUiValueNames, validComponentPropsTargets };
}

/** Flatten a resolved ts.Type into [{name, optional, typeText, jsDoc, defaultFromJsDoc}]. */
export function flattenProps(checker, type) {
  if (!type) return [];
  const props = checker.getPropertiesOfType(type);
  const out = [];
  for (const sym of props) {
    const name = sym.getName();
    const decl = sym.valueDeclaration || (sym.declarations && sym.declarations[0]);
    const optional = !!(sym.flags & ts.SymbolFlags.Optional) || (decl && decl.questionToken != null);
    let typeText = 'unknown';
    try {
      const t = decl ? checker.getTypeOfSymbolAtLocation(sym, decl) : checker.getTypeOfSymbol(sym);
      typeText = checker.typeToString(t, decl, ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.InTypeAlias);
    } catch {
      // best-effort; some synthetic/complex members can throw during typeToString
    }
    const docComment = ts.displayPartsToString(sym.getDocumentationComment(checker));
    const jsDocTags = sym.getJsDocTags(checker).map((t) => ({
      name: t.name,
      text: t.text ? ts.displayPartsToString(t.text) : '',
    }));
    const defaultTag = jsDocTags.find((t) => t.name === 'default');
    // Deliberately a *single token* match (stops at the first whitespace or
    // backtick): BeeUI's JSDoc prose isn't always backtick-quoted around the
    // default value ("Defaults to false." — no backticks), so a wider
    // "capture up to the next period" regex swallows the rest of the
    // sentence whenever the value itself is followed by more prose before
    // the next period (e.g. "Defaults to false; drive visibility with a
    // controlled pair instead."). A single-token capture is conservative:
    // it can under-match (miss multi-word defaults) but cannot fabricate a
    // garbled multi-clause "default value" out of unrelated prose.
    const proseDefaultMatch = docComment.match(
      /[Dd]efaults? to `?(?:'([^']*)'|"([^"]*)"|([^\s`.,;]+))`?/
    );
    const STOPWORDS = new Set(['the', 'a', 'an', 'no', 'none', 'this', 'that', 'current', 'whatever', 'value', 'its']);
    let jsDocDefault = defaultTag ? defaultTag.text.trim() : null;
    if (!jsDocDefault && proseDefaultMatch) {
      const quoted = proseDefaultMatch[1] ?? proseDefaultMatch[2];
      const token = quoted != null ? `'${quoted}'` : proseDefaultMatch[3].replace(/[.,;)]+$/, '');
      const bare = (quoted ?? proseDefaultMatch[3] ?? '').toLowerCase();
      if (token && !STOPWORDS.has(bare)) jsDocDefault = token;
    }
    out.push({ name, optional, typeText, docComment, jsDocDefault });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}
